package com.ksefhelper.audit;

public enum AuditEventType {
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGOUT,
    EMAIL_VERIFIED,
    PASSWORD_RESET,
    ACCOUNT_DISABLED,
    ACCOUNT_ENABLED,
    ACCOUNT_DELETED,
    ORGANIZATION_CREATED,
    ORGANIZATION_SELECTED,
    ORGANIZATION_MEMBER_INVITED,
    ORGANIZATION_DATA_EXPORTED,
    ORGANIZATION_DELETED,
    INVOICE_UPLOADED,
    INVOICE_REVALIDATED,
    INVOICE_DOWNLOADED,
    INVOICE_DELETED,
    INVOICE_RETENTION_DELETED
}
